version: '3.5'

services:
  traefik:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    networks:
      - chartmuseum-net
    ports:
      - "80:80"     # The HTTP port
      - "443:443"     # The HTTPS port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/${TRAEFIK_CONFIG:-traefik_dev.toml}:/traefik.toml
      - ./traefik/acme.json:/acme.json
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    container_name: chartmuseum
    networks:
     - chartmuseum-net
    ports:
     - 8080:8080
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: microsoft
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_ACCESS_KEY: ${AZURE_STORAGE_ACCESS_KEY}
      STORAGE_MICROSOFT_CONTAINER: charts
      STORAGE_MICROSOFT_PREFIX: ""

networks:
  chartmuseum-net: